vich_uploader:
    db_driver: orm

    mappings:
       slider_images:
           uri_prefix: /upload/slider
           upload_destination: '%kernel.project_dir%/public/upload/slider'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       page_pdf:
           uri_prefix: /upload/pdf
           upload_destination: '%kernel.project_dir%/public/upload/pdf'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       resource_images:
           uri_prefix: /upload/resource
           upload_destination: '%kernel.project_dir%/public/upload/resource'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       product_images:
           uri_prefix: /upload/product
           upload_destination: '%kernel.project_dir%/public/upload/product'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
       
       category_images:
           uri_prefix: /upload/category
           upload_destination: '%kernel.project_dir%/public/upload/category'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
